### ISSUE TITLE
How large can the array be?

### ISSUE THREAD

**Issue by vahidvdn** [rkhayyat/nativescript-swipe-card#2]
Hi. Thanks for this awesome plugin. How large can the entry array be? Is it something like a virtual scroller that recycles the layout? Or if array will be big, it causes a memory leak?

**Comment by rkhayyat** [comment]
Hi @vahidvdn and thx in your interest in the plugin, actually when I built the swipe-card I was not aware of this issue (memory) so actually I use a simple array. but normally unless your array is extremely big, it should not break. other idea, is to handle the recycling in your app, so that you don't load the array in one shot

**Comment by vahidvdn** [comment]
@rkhayyat The ideal is always to load just a few items in the stack. Btw, thank you.
